# Generated by Django 4.2.5 on 2025-01-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('buy', 'Buy')], max_length=20)),
            ],
        ),
    ]
